### ISSUE TITLE
making plant database with error

### ISSUE THREAD

**Issue by zouminghong** [qiyunlab/HGTector#116]
Hello,Qiyun！Thank you in advance for developing such an amazing tool.
I meet an error when I create the plant database and I'm a little confused about it.

(hgtector) [zou@localhost ~]$ hgtector database -o db_dir --cats plant --sample 5 --threads 32

Database building started at 2023-05-05 03:04:58.094068.
  Using local file taxdump.tar.gz.
Reading NCBI taxonomy database... done.
  Total number of TaxIDs: 2502076.
Downloading RefSeq assembly summary... done.
Reading RefSeq assembly summary... done.
  Total number of genomes: 301820.
Genome categories: plant
Downloading genome list per RefSeq category...
  plant: 160
Done.
  Total number of genomes in categories: 160.
Filtering genomes...
Traceback (most recent call last):
  File "/home/zou/anaconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/zou/anaconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/zou/anaconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 134, in __call__
    self.filter_genomes()
  File "/home/zou/anaconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 394, in filter_genomes
    self.df['accnov'] = self.df['accession'].str.split('.', 1).str[0]
  File "/home/zou/anaconda3/envs/hgtector/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 were given

Could you please help me with this issue?
Looking forward your replay.

**Comment by ZQYYRA** [comment]
@zouminghong 
Do you solve this error? I also get this error when I run this command to download database.
Good luck for you!
