### ISSUE TITLE
Remote search timeout error

### ISSUE THREAD

**Issue by molamber** [qiyunlab/HGTector#121]
Hi, 
I'm trying to run HGTector on a bacterial genome and I'm having a problem with the hgtector search function.

Every time I run the code hgtector search -i input.faa -o . I have this error : 

"Number of queries: 1096.
Submitting 30 queries for search. RID: 8VM93XA8013................WARNING: Remote search timeout.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/opt/anaconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/opt/anaconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 164, in __call__
    res = self.search_wf(
          ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 686, in search_wf
    res = self.remote_search(seqs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 1585, in remote_search
    raise ValueError(
ValueError: Remote search failed after 1 trials."

I also tried with the example file containing 100 proteins and with only 20 proteins, and i'm having everytime the same error. 

I'm running HGTector on a MacOS machine, and I installed it with conda. 

I'm a PhD student and new to coding, so I'd like to thank you in advance for your help, 

Sincerely, 

Molamber

**Comment by molamber** [comment]
Hi, 

Okay thank's for your answer, i'll try that ! :)
