### ISSUE TITLE
Fails at diamond blast, type error: expected string

### ISSUE THREAD

**Issue by kaw97** [qiyunlab/HGTector#127]
I'm trying to run HGTector for the first time, and encountering problems at the diamond blast step. I'd very much appreciate any troubleshooting help you can give.

I have successfully set up my databases, but when I run hgtector search, I get the following error:

`Traceback (most recent call last):
  File "/home/kyle/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/kyle/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/kyle/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 171, in __call__
    res = self.search_wf(
          ^^^^^^^^^^^^^^^
  File "/home/kyle/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 686, in search_wf
    res = self.diamond_search(seqs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 1530, in diamond_search
    ec, out = run_command(' '.join(cmd), merge=False)
                          ^^^^^^^^^^^^^
TypeError: sequence item 5: expected str instance, NoneType found`

it appears to be happening when it starts the first blast search. This is the last output from my run:
`  GCA_002878455.fa: 5677 proteins.
  GCA_001758765.fa: 5426 proteins.
Done. Read 261098 proteins from 47 samples.
Dropping sequences shorter than 30 aa... done.
Initiating custom taxonomy database... done.
Batch homology search of GCA_000013625.fa started at 2023-09-15 17:28:44.124043.
Number of queries: 3838.`

Thanks a ton!
Kyle Wolf

**Comment by kaw97** [comment]
The output/error files:

[hgtector.515643.out.txt](https://github.com/qiyunlab/HGTector/files/12629226/hgtector.515643.out.txt)
[hgtector.515643.err.txt](https://github.com/qiyunlab/HGTector/files/12629227/hgtector.515643.err.txt)

**Comment by qiyunzhu** [comment]
Hello @kaw97 Kyle, thank you for using our program. I checked the code and located a plausible cause. However, I cannot reproduce it. Can you please let me know the specific `hgtector search` command you used? I suspect that there were custom parameters which were incorrectly casted into `None` by the program.

**Comment by kaw97** [comment]
> Hello @kaw97 Kyle, thank you for using our program. I checked the code and located a plausible cause. However, I cannot reproduce it. Can you please let me know the specific `hgtector search` command you used? I suspect that there were custom parameters which were incorrectly casted into `None` by the program.

Certainly! Thanks a bunch. I am running it with:

`hgtector search -i /media/bigdrive1/kyle/janthino/input_genomes2/test_download/janthino_genomes/annotated_analysis/faa/ -o search -m diamond -p 16`

**Comment by qiyunzhu** [comment]
@kaw97 Thanks! This is the default command, and I don't know where could a `None` pop up. Just in case, did you edit the [configuration file](https://github.com/qiyunlab/HGTector/blob/master/doc/config.md) to remove some default values? To further debug, you can open the file:

```
/home/kyle/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py
```

Find [this line](https://github.com/qiyunlab/HGTector/blob/master/hgtector/search.py#L1536)

```python
        ec, out = run_command(' '.join(cmd), merge=False)
```

Insert a new line before it. The content is:

```python
        print(cmd)
```

Then run the program as you did. Before the same error happens, the program will print out the command. Let me see it so that I can check which parameter was incorretly assigned as `None`. Thanks!

**Comment by 18295478799** [comment]
hgtector search -i protein.fa -o . -m diamond -p 16 -d /data/maqin/Project/HGT/HGTector/hgtdb_20230102/diamond/db.dmnd -t /data/maqin/Project/HGT/HGTector/hgtdb_20230102/taxdump/
Homology search started at 2024-11-21 14:47:15.482917.
Settings:
  Search method: diamond.
  Self-alignment method: native.
  Remote fetch enabled: no.
Reading input proteins...
  protein: 2 proteins.
Done. Read 2 proteins from 1 samples.
Dropping sequences shorter than 30 aa... done.
Reading local taxonomy database... done.
  Read 51329 taxa.
Batch homology search of protein started at 2024-11-21 14:47:15.592765.
Number of queries: 2.
Traceback (most recent call last):
  File "/home/maqin/anaconda3/bin/hgtector", line 4, in <module>
    __import__('pkg_resources').run_script('hgtector==2.0b3', 'hgtector')
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 96, in <module>
    main()
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 35, in main
    module(args)
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 177, in __call__
    res = self.search_wf(
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 692, in search_wf
    res = self.diamond_search(seqs)
  File "/home/maqin/anaconda3/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/search.py", line 1539, in diamond_search
    raise ValueError(f'diamond failed with error code {ec}.')
ValueError: diamond failed with error code 1.
I added print (CMD) and also reported an error
