### ISSUE TITLE
hgtdb_20170630.tar.xz

### ISSUE THREAD

**Issue by YingyingZ9** [qiyunlab/HGTector#130]
I am trying to do "download a [pre-built database](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#pre-built-databases) as of 2023-01-02, and [compile](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#Manual-compiling) it.", but I compile database "hgtdb_20170630.tar.xz" , it doesn't have "taxon.map.gz". And what should I do?

**Comment by qiyunzhu** [comment]
Hello @YingyingZ9 The 2017 database was too old and it was designed for HGTector v0.x. It won't work with the current HGTector. With that being said, it may be possible for you to hack the database to make it compatible.

**Comment by YingyingZ9** [comment]
> Hello @YingyingZ9 The 2017 database was too old and it was designed for HGTector v0.x. It won't work with the current HGTector. With that being said, it may be possible for you to hack the database to make it compatible.

Thank you for your reply. I've encountered a new problem，when I enter it “hgtector search -i ****/hgtdb_20230102/japonica/*.faa.gz -o search_dir -m diamond -p 16 -d ****/hgtdb_20230102/diamond/db.dmnd -t ****/hgtdb_20230102/taxdump” ，I got this result：Homology search started at 2023-10-18 09:08:28.411085.
Settings:
  Search method: diamond.
  Self-alignment method: native.
  Remote fetch enabled: no.
Reading input proteins...
  japonica: 55801 proteins.
Done. Read 55801 proteins from 1 samples.
Dropping sequences shorter than 30 aa... done.
Reading local taxonomy database... done.
  Read 51329 taxa.
Batch homology search of japonica started at 2023-10-18 09:08:29.332318.
Number of queries: 55786.
Traceback (most recent call last):
  File "/home/zhouyingying/data_HD/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/zhouyingying/data_HD/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/zhouyingying/data_HD/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 177, in __call__
    res = self.search_wf(
          ^^^^^^^^^^^^^^^
  File "/home/zhouyingying/data_HD/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 692, in search_wf
    res = self.diamond_search(seqs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhouyingying/data_HD/miniconda3/envs/hgtector/lib/python3.11/site-packages/hgtector/search.py", line 1539, in diamond_search
    raise ValueError(f'diamond failed with error code {ec}.')
ValueError: diamond failed with error code 1.
