### ISSUE TITLE
An error occurred downloading the database

### ISSUE THREAD

**Issue by taotaoyuan** [qiyunlab/HGTector#134]
Database building started at 2023-12-07 17:48:50.178062.
Reading NCBI taxonomy database... done.
  Total number of TaxIDs: 2545202.
Reading RefSeq assembly summary... done.
  Total number of genomes: 344111.
Genome categories: bacteria, archaea, fungi, viral, plant
Running Command: rsync --list-only --no-motd rsync://ftp.ncbi.nlm.nih.gov/genomes/refseq/
Downloading genome list per RefSeq category...
  bacteria: 325433
  archaea: 1889
  fungi: 564
  viral: 14992
  plant: 175
Done.
Traceback (most recent call last):
  File "/home/lx_sky6/software/miniconda3/envs/neoHGT/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '# assembly_accession'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/neoHGT/scripts/neoHGT", line 88, in <module>
    main()
  File "/home/lx_sky6/yt/soft/neoHGT/scripts/neoHGT", line 27, in main
    module(args)
  File "/home/lx_sky6/software/miniconda3/envs/neoHGT/lib/python3.11/site-packages/neoHGT-2.0b3-py3.11.egg/neoHGT/database.py", line 153, in __call__
      self.retrieve_categories()
  File "/home/lx_sky6/software/miniconda3/envs/neoHGT/lib/python3.11/site-packages/neoHGT-2.0b3-py3.11.egg/neoHGT/database.py", line 393, in retrieve_categories
    self.df = self.df[self.df['# assembly_accession'].isin(asmset)]
                      ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lx_sky6/software/miniconda3/envs/neoHGT/lib/python3.11/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lx_sky6/software/miniconda3/envs/neoHGT/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: '# assembly_accession'

**Comment by Mohsin0911** [comment]
Am also getting this issue, if you got any solution, please share here

**Comment by zzlzef** [comment]
Am also getting this issue, if you got any solution, please share here

**Comment by qiyunzhu** [comment]
Hi @zzlzef The issue was fixed in the master branch. If you update HGTector with:

```bash
pip install git+https://github.com/qiyunlab/HGTector.git
```

It should work. Thanks!
