### ISSUE TITLE
Error while downloading genomes for the database

### ISSUE THREAD

**Issue by matrs** [qiyunlab/HGTector#74]
Hello, 
thanks for this software. I'm using `hgtector-2.0b3`.

I'm getting this `ftplib` error at different points of the download process. I've run it a few times now and I haven't been able to finish the task. 
I'm using:
`hgtector database -o $db_dir --default --overwrite --threads 28`

```python
Traceback (most recent call last):
  File "/home/miniconda3/envs/bif2020.1/bin/hgtector", line 96, in <module>
    main()
  File "/home/miniconda3/envs/bif2020.1/bin/hgtector", line 35, in main
    module(args)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/site-packages/hgtector/database.py", line 137, in __call__
    self.download_genomes()
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/site-packages/hgtector/database.py", line 549, in download_genomes
    self.ftp.retrbinary(
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 238, in getresp
    resp = self.getmultiline()
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 224, in getmultiline
    line = self.getline()
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 212, in getline
    raise EOFError
EOFError
```

I'm guessing some downloaded file is corrupted, but I don't know how to try to avoid this problem besides using `--rewrite`

**Comment by qiyunzhu** [comment]
Hello @matrs Thanks for your interest in the program. Recently I also noticed this issue, likely because some files downloaded from the server are corrupted. I made a patch to skip those genomes. You can update by:

```bash
pip install -U git+https://github.com/qiyunzhu/HGTector.git@dberr
```

I will appreciate that you try and let me know if the problem is solved!

**Comment by qiyunzhu** [comment]
Alternatively, you can download the pre-made database. See [here](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#default-protocol).

**Comment by matrs** [comment]
> Hello @matrs Thanks for your interest in the program. Recently I also noticed this issue, likely because some files downloaded from the server are corrupted. I made a patch to skip those genomes. You can update by:
> 
> ```shell
> pip install -U git+https://github.com/qiyunzhu/HGTector.git@dberr
> ```
> 
> I will appreciate that you try and let me know if the problem is solved!

I uninstalled  the previous version and I tried this but I'm getting the exact same error. I'll try the pre-made database. The reason I didn't tried it before was that I'm working on a publication (I only need bacteria and maybe archea) and the date of this pre-made db seems a bit "old" to me,  given the pace at which bacterial genomes are deposited in the NCBI. 

Thank you for your help

**Comment by qiyunzhu** [comment]
Hello @matrs I looked into your error message and made another patch, which can retry if a file cannot be completed retrieved from the server, or skip after five unsuccessful trials. If you uninstall and reinstall using the same command I posted you should be able to get the patch. Hope it works. I cannot test if because the error didn't happen to me. Will appreciate if you can let me know if that works.

**Comment by matrs** [comment]
Hello @qiyunzhu . I tried the latest code and i got a broken pipe error this time:

```python
Traceback (most recent call last):
  File "/home/miniconda3/envs/bif2020.1/bin/hgtector", line 96, in <module>
    main()
  File "/home/miniconda3/envs/bif2020.1/bin/hgtector", line 35, in main
    module(args)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/site-packages/hgtector/database.py", line 137, in __call__
    self.download_genomes()
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/site-packages/hgtector/database.py", line 551, in download_genomes
    self.ftp.retrbinary(cmd, f.write)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 424, in retrbinary
    self.voidcmd('TYPE I')
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 279, in voidcmd
    self.putcmd(cmd)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 201, in putcmd
    self.putline(line)
  File "/home/miniconda3/envs/bif2020.1/lib/python3.8/ftplib.py", line 196, in putline
    self.sock.sendall(line.encode(self.encoding))
BrokenPipeError: [Errno 32] Broken pipe
```


I really don't know why `ftp.retrbinary` successfully retrieves 0 byte files (thi sis what i see). Anyways, I created a table with the sampled genomes to download them with rsync. I created it from the line [518 in  database.py](https://github.com/qiyunlab/HGTector/blob/453ee04308a0aab2a4c1d2faaa794b1d3cd3706c/hgtector/database.py#L518). Maybe you can tell me if this is the correct object from which to get the list of genomes used to create the db. In this case is a table with `31968` rows (i'm using only bacteria).

```python
self.df.drop(columns=['al_seq', 'rc_seq'], inplace=True)
self.df.to_csv('table_path.csv', index=False)
```

I'm placing the faa files in `faa/` and  I expect to pass this list to:

```
hgtector database -o $db_dir --cats bacteria --sample 1 --rank species \
 --reference --representative --compile diamond --threads 28
```

**Comment by qiyunzhu** [comment]
Hello @matrs I eventually got time to fix this issue. Now the program will reconnect the NCBI FTP server if an `EOFError` is encountered. Tested and working. I agree with you that building a list of URLs and let the user download them using `rsync` is a good idea, and is also the NCBI-recommended way. I will add this feature in the next pull request.

**Comment by matrs** [comment]
Thanks !
