### ISSUE TITLE
Error in database command

### ISSUE THREAD

**Issue by zakisaati** [qiyunlab/HGTector#77]
Hello,

I have hgtector 2.0b3 installed and Diamond 0.9.26.

I ran the database command, but it returns an error. This is the command and the message:

hgtector database --output database --cats all --sample 1 --rank species --reference --representative --compile diamond
Database building started at 2021-03-02 19:41:31.820355.
Connecting to the NCBI FTP server... done.
  Using local file taxdump.tar.gz.
Reading NCBI taxonomy database...Traceback (most recent call last):
  File "/home/zaki/miniconda3/bin/hgtector", line 96, in <module>
    main()
  File "/home/zaki/miniconda3/bin/hgtector", line 35, in main
    module(args)
  File "/home/zaki/miniconda3/lib/python3.7/site-packages/hgtector/database.py", line 119, in __call__
    self.retrieve_taxdump()
  File "/home/zaki/miniconda3/lib/python3.7/site-packages/hgtector/database.py", line 262, in retrieve_taxdump
    f.extract('names.dmp', self.tmpdir)
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 2033, in extract
    tarinfo = self.getmember(member)
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 1752, in getmember
    tarinfo = self._getmember(name)
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 2327, in _getmember
    members = self.getmembers()
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 1763, in getmembers
    self._load()        # all members, we first have to
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 2350, in _load
    tarinfo = self.next()
  File "/home/zaki/miniconda3/lib/python3.7/tarfile.py", line 2281, in next
    self.fileobj.seek(self.offset - 1)
  File "/home/zaki/miniconda3/lib/python3.7/gzip.py", line 368, in seek
    return self._buffer.seek(offset, whence)
  File "/home/zaki/miniconda3/lib/python3.7/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/home/zaki/miniconda3/lib/python3.7/gzip.py", line 471, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid code lengths set

I am aware that there is a pre-built default database for download, but I need a broader database, not only microbial database. I tryed with this file (and following your compiling codes and so on), and it worked properly, but in order to compile the complete databases I need to run the database comand with "--cats all" or to download from somewhere the complete database, if any.

Could you please help me with this error or to provide me some link for download the complete database?

Thank you very much in advance

**Comment by Mingye-Peng** [comment]
Hello,

I also have the same problem, do not know how to solve it?

**Comment by zakisaati** [comment]
No, I was unable to find a solution, sorry

**Comment by qiyunzhu** [comment]
Hello all @zakisaati @Mingye-Peng Thanks for reporting this issue. I just tested and didn't experience the same problem. I am suspecting either of the following reasons:

1. At a particular time the NCBI taxdump file is corrupt. To test this, you can remove the `database` directory and try the same command again.

2. What's the operating system you are using? I tested both Linux and macOS and both worked fine. But I suspect that Windows or WSL might have a different tar library that causes the problem.
