### ISSUE TITLE
EOF error in database import

### ISSUE THREAD

**Issue by apoorva004** [qiyunlab/HGTector#80]
Hi Qiyunzhu, 
I have been trying to compile the default database for HGT detection in my genome sequence 
I used the following code
 !hgtector database --output output_dir --cats microbe --sample 1 --rank species --reference --representative --compile diamond

After importing and sorting the files from NCBI, it gives me this error: 
Traceback (most recent call last):
  File "/usr/local/bin/hgtector", line 96, in <module>
    main()
  File "/usr/local/bin/hgtector", line 35, in main
    module(args)
  File "/usr/local/lib/python3.7/site-packages/hgtector/database.py", line 137, in __call__
    self.download_genomes()
  File "/usr/local/lib/python3.7/site-packages/hgtector/database.py", line 541, in download_genomes
    f'RETR {remote_dir}/{fname}', f.write)
  File "/usr/local/lib/python3.7/ftplib.py", line 442, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.7/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.7/ftplib.py", line 365, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/local/lib/python3.7/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.7/ftplib.py", line 236, in getresp
    resp = self.getmultiline()
  File "/usr/local/lib/python3.7/ftplib.py", line 222, in getmultiline
    line = self.getline()
  File "/usr/local/lib/python3.7/ftplib.py", line 210, in getline
    raise EOFError
EOFError

Since I am new to the coding, It will be helpful if you can explain this error to me. 

I can try manual compiling too, but instructions are bin unclear. 
Downloaded file is in tar.xz format 
should we compile using the following code?
echo $'accession\taccession.version\ttaxid' > prot.accession2taxid
zcat taxon.map.gz | awk -v OFS='\t' '{split($1, a, "."); print a[1], $1, $2}' >> prot.accession2taxid

diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db

rm prot.accession2taxid

Where to we insert the downloaded file? What will be the output? how do we use it during HGT search ?

**Comment by qiyunzhu** [comment]
Hello @apoorva004 I eventually got time to fix the database download issue. It should work now. Sorry for the long delay...
