### ISSUE TITLE
TaxID 426428 is not found in taxonomy database

### ISSUE THREAD

**Issue by sunnycqcn** [qiyunlab/HGTector#86]
Hello Qiyun,
When I used command as following:
`hgtector analyze -i L001_L001.proteins.tsv -o . -t database/taxdump --bandwidth auto`
I met the error as following:
`Analysis started at 2021-12-03 10:15:57.662288.
Reading local taxonomy database...
Done. Read 26558 taxa.
Reading homology search results...
  L001_L001.proteins: 13277 proteins.
Done. Read search results of 1 samples.
Auto-inferring plausible taxIds for input genomes based on taxonomy of search results...
Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 422, in _get_taxon
    return taxdump[tid]
KeyError: '426428'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 364, in assign_taxonomy
    tid, cov = self.infer_genome_tax(
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 420, in infer_genome_tax
    for tid in get_lineage(bestid, taxdump):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 659, in get_lineage
    taxon = _get_taxon(cid, taxdump)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 424, in _get_taxon
    raise ValueError(f'TaxID {tid} is not found in taxonomy database.')
ValueError: TaxID 426428 is not found in taxonomy database.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 141, in __call__
    self.assign_taxonomy()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 368, in assign_taxonomy
    raise ValueError(f'Cannot auto-infer taxonomy for {sid}.'
ValueError: Cannot auto-infer taxonomy for L001_L001.proteins. Please specify manually.
`
In fact, my data is good before I updated HGTector.
Thanks,
Fuyou

**Comment by qiyunzhu** [comment]
Likely because the protein sequence database and the taxdump are not compatible. For example, if you did search using the old database, and do the analysis using the new database, there could be some missing TaxIDs.
