### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by manik-123** [qiyunlab/HGTector#88]
Hello,
I keep trying to download the database but every time is showing the error, can you please help
Traceback (most recent call last):
  File "/project/liuguohong/anaconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/project/liuguohong/anaconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/site-packages/hgtector/database.py", line 137, in __call__
    self.download_genomes()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/site-packages/hgtector/database.py", line 540, in download_genomes
    self.ftp.retrbinary(
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 436, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 393, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 359, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 281, in sendcmd
    return self.getresp()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 244, in getresp
    resp = self.getmultiline()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 230, in getmultiline
    line = self.getline()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.9/ftplib.py", line 218, in getline
    raise EOFError
EOFError

**Comment by qiyunzhu** [comment]
Hello @manik-123 Please update to the latest version of HGTector ([2.0b3](https://github.com/qiyunlab/HGTector/releases/tag/2.0b3)), which has fixed this problem. Alternatively, you can download the pre-built [database](https://www.dropbox.com/s/tszxy9etp52id3u/hgtdb_20211121.tar.xz?dl=0) (hosted at Dropbox).

**Comment by manik-123** [comment]
Thank you for your quick response, 
conda create -n hgtector -c conda-forge python=3 pyyaml pandas matplotlib scikit-learn bioconda::diamond
conda activate hgtector
i updated it using pip install -U git+https://github.com/DittmarLab/HGTector.git@2.0b3
and used hgtector database -o db_dir --default
but still its the same error.
I want to have the recent data base, so is my pipeline correct

**Comment by qiyunzhu** [comment]
You may have to completely delete the conda environment and create it again. The trick is that when I updated the program, I didn't change the version number, so pip may use what's already cached in the local directory.

**Comment by manik-123** [comment]
Okay Thank you so much

**Comment by manik-123** [comment]
Its working, thank you

**Comment by qiyunzhu** [comment]
Glad to know that!

**Comment by manik-123** [comment]
Hello,
I have downloaded the database, seems I have some issue again
****************************
superkingdom: 3.
  kingdom: 1.
  phylum: 75.
  class: 148.
  order: 343.
  family: 793.
  genus: 3802.
  species: 16258.
Genome lineages written to lineages.txt.
Genome metadata written to genomes.tsv.
Taxonomy database written to taxdump/.
Protein-to-taxonomy map written to taxon.map.gz.
Build DIAMOND database...
Traceback (most recent call last):
  File "/project/liuguohong/anaconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/project/liuguohong/anaconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 169, in __call__
    self.compile_database()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 830, in compile_database
    self.build_diamond_db()
  File "/project/liuguohong/anaconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 884, in build_diamond_db
    raise ValueError(f'diamond failed with error code {ec}.')
ValueError: diamond failed with error code 1.

**Comment by qiyunzhu** [comment]
What's the version of your DIAMOND? You can do `diamond version` to find out.

**Comment by manik-123** [comment]
i used
conda install -c bioconda diamond to install and then updated 
conda update diamond,
but the version is still diamond version 0.9.14

**Comment by qiyunzhu** [comment]
I see. DIAMOND has long had some version issue with conda. You perhaps need to try to install DIAMOND manually, e.g., compile it from the source code. HGTector may not work with old DIAMOND versions.

**Comment by manik-123** [comment]
Got it, 
I will deal and update you,
Thank you for the response, good night.

**Comment by manik-123** [comment]
Dear qiyunzhu,
Its working now. Its a very good and hassle free  software. As a user i would request one thing. It gives the donar and gene but it would be more effective if we get a gene annotated file. Its just a suggestion and thank you for this software.

**Comment by manik-123** [comment]
I mean to say,
In o55h7.tsv it is mentioned as  
 ID: WP_000064228.1
# Length: 714
# Product: methylmalonyl-CoA mutase

when we run analyze the out is 
Protein | Score | Donor

is it possible 
Protein | Score | Donor l product
WP_000064228.1l 0.691785l 1224l methylmalonyl-CoA mutase (This is just an example)
I mean to say is the product name and donar name is possible in final out put.

**Comment by qiyunzhu** [comment]
I see your point. I am not too sure... because 1) it is easy for the user
to add this information if needed, 2) not all proteins have this
information, e.g., a user-predicted one might just have ID but not
product...

**Comment by manik-123** [comment]
I get it now, yes as you said some might have ID but not product. Thank you for all your support and every thing is going good.

**Comment by qiyunzhu** [comment]
You are welcome! I hope your research will be smooth and successful!
