### ISSUE TITLE
Cannot download data from NCBI refseq

### ISSUE THREAD

**Issue by YimingLiu000** [qiyunlab/HGTector#98]
Hi,

I am using HGTector2 and constructing a new database with the following command: 
hgtector database -t 9606 -o ./Hominidae --compile diamond --threads 12 --retries 5 --delay 1 --timeout 5

Then the following sentence showed on the screen without change and the download file kept empty.
Database building started at 2022-08-08 23:00:10.549497.
Downloading NCBI taxonomy database...

After KeyboardInterrupt, the result showed:
CTraceback (most recent call last):
  File "/home/kuihuadufu/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/kuihuadufu/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/kuihuadufu/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 124, in __call__
    self.retrieve_taxdump()
  File "/home/kuihuadufu/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 263, in retrieve_taxdump
    run_command(f'rsync -Ltq {server}/{rfile} {self.down}')
  File "/home/kuihuadufu/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/util.py", line 237, in run_command
    res = subprocess.run(
  File "/home/kuihuadufu/miniconda3/envs/hgtector/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/kuihuadufu/miniconda3/envs/hgtector/lib/python3.10/subprocess.py", line 1139, in communicate
    stdout = self.stdout.read()
KeyboardInterrupt

I have no idea about this situation. Any help or suggestions you may have would be greatly appreciated.

**Comment by qiyunzhu** [comment]
Hello @YimingLiu000 Thanks for your interest in our program. This scenario may be because the Internet connection to the NCBI FTP server is broken. To check, can you run the following command in a terminal?

```bash
wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
```

PS: I don't think a database of human sequences will be useful for HGT detection... Unless you just wanted to test if the program runs.

**Comment by YimingLiu000** [comment]
Yes, I can run it and download this file successfully.

**Comment by YimingLiu000** [comment]
After a long wait, the command finally works, thanks for your suggestion! I think when the screen shows the statement below, displaying the corresponding progress bar may be a better option.

Downloading non-redundant genomic data from NCBI...

**Comment by qiyunzhu** [comment]
Hello @YimingLiu000 Sorry for the late response. I guess this [section](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#manual-downloading) will help. It generates a list of URLs and let you manually download them. If `rsync` does not work, you may try `wget` or other approaches.
